### ISSUE TITLE
eth-tester[pyethereum16] filter 'toBlock' is exclusive

### ISSUE THREAD

**Issue by palango** [ethereum/eth-tester#75]
* Version: `eth-tester==0.1.0b21`
* Python: 3.6
* OS: osx

### What was wrong?

I'm not sure where to report this best, but as it happens on a eth-tester based chain I think this is a good place.

The issue is that creating a filter with the `toBlock`parameter set to a block number behaves differently when eth-tester with the pyethereum1.6 backend than with geth.

Geth's `toBlock` is inclusive while the eth-tester filter excludes it. Even though this is a backend related problem this should probably be handled by eth-tester or the backend plugins and tested.

### How can it be fixed?

Handle filter behaviour and test that `toBlock` is inclusive.

**Comment by pipermerriam** [comment]
Since all filtering logic is handled locally in `eth-tester` this is *likely* as simple as changing some comparisons from `<` to `<=` and updating some tests.

**Comment by boneyard93501** [comment]
just ran into the same issue. i should have some time early next week to take a stab at this.

**Comment by boneyard93501** [comment]
@pipermerriam @carver 
i've had a look at that and i don't think it's in eth tester:
```bash
# eth_tester/utils/filters.py
114      elif is_integer(to_block):
115        return is_integer(block_number) and block_number <= to_block
```
after some detours since i failed to replicate my issue (infura, Geth/v1.8.3-patched-cad76670/linux-amd64/go1.9.2) i upgraded web3 and happened to run into this:
``` python
>>> from web3 import Web3, EthereumTesterProvider
>>> from eth_tester.backends import PyEthereum16Backend
>>> w3 = Web3(EthereumTesterProvider(PyEthereum16Backend))
>>> w3.isConnected()
True
>>> w3.eth.accounts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/eth.py", line 105, in accounts
    return self.web3.manager.request_blocking("eth_accounts", [])
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/manager.py", line 103, in request_blocking
    response = self._make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/manager.py", line 86, in _make_request
    return request_func(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/validation.py", line 46, in middleware
    return make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/providers/eth_tester/middleware.py", line 322, in middleware
    return make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/fixture.py", line 12, in middleware
    return make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/providers/eth_tester/main.py", line 46, in make_request
    response = delegator(self.ethereum_tester, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/93501/localDev/source-code/forks/web3.py/web3/providers/eth_tester/defaults.py", line 36, in call_eth_tester
    return getattr(eth_tester, fn_name)(*fn_args, **fn_kwargs)
  File "/Users/93501/.virtualenvs/web3-4.1/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
TypeError: get_accounts() missing 1 required positional argument: 'self'
>>> w3.version.api
'4.1.0'
>>>
```
this maybe due to a version incompatibility with the 4.10 dev install:
```python
py-evm]==0.1.0-beta.23->web3==4.1.0)
**py-evm 0.2.0a14 has requirement eth-tester==0.1.0b21, but you'll have eth-tester 0.1.0b23 which is incompatible.
```
but i doubt it. 
regardless, i started to look at the backend but ran out of time. i'm out of pocket for a couple days but should be able to re-engage wednesday.

**Comment by boneyard93501** [comment]
it's been working for me. i'm certainly willing to look some more but i'd need more info to be able to recreate the issue. in my case, i probably forgot to press the return key in one of the terminals.

**Comment by kclowes** [comment]
Closing since pyethereum is no longer maintained.
